In [ ]:
# sample tiles from scanb_malmo with philips and xr1/2

In [1]:
import pandas as pd
import numpy as np


pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', 0)   # show all columns
pd.set_option('display.width', 0)         # no line wrapping

In [ ]:
# df for feature extraction

# # Fast CSV read & filter
# csv_path = 
# usecols = [col_name, "scanner_model_new", "split", "blur"]
# df = pd.read_csv(csv_path, usecols=usecols, dtype={col_name:str, "scanner_model_new":str, "split":str})
# df = df.dropna(subset=[col_name, "scanner_model_new", "split"]).copy()
# df["path"] = df[col_name].astype(str).str.strip()
# df = df[df["blur"]>250]

In [2]:

# Define stratified split function

def stratified_split_one_df_tile(df, var, n_train=10000, n_test=2000, random_state=24, split_col="split"):
    """
    Returns one DataFrame containing only the selected rows, with a `split` column.
    - var: column to stratify on (e.g., 'scanner_model')
    - n_train, n_test: per-stratum targets
    - If a stratum has fewer rows than requested, it will take as many as possible (train first).
    """
    rng = random_state
    df_shuf = df.sample(frac=1, random_state=rng)  # shuffle once for reproducibility

    labels = []  # collect (index, split_label)

    for level, g in df_shuf.groupby(var, sort=False, group_keys=False):
        need_train = n_train
        need_test  = n_test
        total = len(g)

        n_train_take = min(need_train, total)
        g_train = g.sample(n=n_train_take, random_state=12)

        g_rest = g.drop(g_train.index)
        n_test_take = min(need_test, len(g_rest))
        g_test = g_rest.sample(n=n_test_take, random_state=12)

        if total < (need_train + need_test):
            print(f"[warn] '{level}': only {total} rows; took train={n_train_take}, test={n_test_take}.")

        labels.extend([(idx, "train") for idx in g_train.index])
        labels.extend([(idx, "test")  for idx in g_test.index])

    # Build output DF of selected rows only, with split column
    selected_idx = [i for i, _ in labels]
    split_map = dict(labels)

    out = df.loc[selected_idx].copy()
    out[split_col] = out.index.map(split_map)

    # sanity prints
    print("\nPer-stratum counts:")
    print(out.groupby([var, split_col]).size().unstack(fill_value=0))

    # ensure no overlap & only requested rows
    assert set(out[split_col].unique()) <= {"train","test"}
    return out




def stratified_split_one_df_slide(df, var, n_train=500, n_test=100, random_state=42, split_col="split"):
    """
    Returns one DataFrame containing only the selected rows, with a `split` column.
    - var: column to stratify on (e.g., 'scanner_model')
    - n_train, n_test: per-stratum targets
    - If a stratum has fewer rows than requested, it will take as many as possible (train first).
    """
    rng = random_state
    df_uniq = df.drop_duplicates(subset=['file_name'])  # ensure one row per WSI
    df_shuf = df_uniq.sample(frac=1, random_state=rng)  # shuffle once for reproducibility
    

    labels = []  # collect (index, split_label)

    for level, g in df_shuf.groupby(var, sort=False, group_keys=False):
        need_train = n_train
        need_test  = n_test
        total = len(g)

        n_train_take = min(need_train, total)
        g_train = g.sample(n=n_train_take, random_state=12)

        g_rest = g.drop(g_train.index)
        n_test_take = min(need_test, len(g_rest))
        g_test = g_rest.sample(n=n_test_take, random_state=12)

        if total < (need_train + need_test):
            print(f"[warn] '{level}': only {total} rows; took train={n_train_take}, test={n_test_take}.")

        labels.extend([(idx, "train") for idx in g_train.index])
        labels.extend([(idx, "test")  for idx in g_test.index])

    # Build output DF of selected rows only, with split column
    selected_idx = [i for i, _ in labels]
    split_map = dict(labels)

    out = df.loc[selected_idx].copy()
    out[split_col] = out.index.map(split_map)

    # sanity prints
    print("\nPer-stratum counts:")
    print(out.groupby([var, split_col]).size().unstack(fill_value=0))

    # ensure no overlap & only requested rows
    assert set(out[split_col].unique()) <= {"train","test"}
    df_train = df[df.file_name.isin(out[out[split_col]=="train"].file_name.unique())]
    df_test = df[df.file_name.isin(out[out[split_col]=="test"].file_name.unique())]

    return out, df_train, df_test

#### Read in first batch of crude tiles

In [2]:
file_path = "/mnt/chime-preprocessed_data/SCANB_Malmo/SCANB_Malmo_224x224/processed-data/SCANB_Malmo_pil_10.4_224px/batches/Batch_1/dataframes/all_tiles_blur.csv"
batch_1 = pd.read_csv(file_path)
batch_1.file_name.nunique()

611

In [5]:
# batch_1 crude tiles with macenko_blur
file_path = "/mnt/chime-preprocessed_data/SCANB_Malmo/SCANB_Malmo_224x224/processed-data/SCANB_Malmo_pil_10.4_224px/batches/Batch_1/dataframes/all_tiles_blur.csv"
batch_1 = pd.read_csv(file_path)

# wsi list with scanner_model
df_wsi = pd.read_csv("/mnt/chime-preprocessed_data/SCANB_Malmo/SCANB_Malmo_224x224/df_batch_SCANB_Malmo_224x224.csv", index_col=False)
len(df_wsi)
df_wsi = df_wsi.rename(columns={"slide_filename": "file_name"})

# merge with tile list
batch_1= pd.merge(batch_1, df_wsi[['file_name', 'scanner_model']], on = 'file_name', how='left')

#mask = (batch_1['tissue_proportion']==1) & (batch_1['macenko_blur']> 500) & (batch_1['scanner_model'].isin(['XR2', 'PHILIPS', 'XR1']))
mask = batch_1['scanner_model'].isin(['XR2', 'PHILIPS', 'XR1']) # make it general to use all tiles 
batch_1_select = batch_1[mask]

print(len(batch_1))
print(len(batch_1_select))


print(batch_1_select.scanner_model.value_counts(normalize=True))
batch_1_select['scanner_model_new'] = np.where(
    batch_1_select['scanner_model'].isin(['XR1', 'XR2']),
    'XR',
    'PHILIPS')


print(f'{batch_1_select.file_name.nunique()}, unique wsis in selected set')

14338543
12494647
scanner_model
PHILIPS    0.522985
XR1        0.273281
XR2        0.203733
Name: proportion, dtype: float64

/tmp/ipykernel_139910/2889109967.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  batch_1_select['scanner_model_new'] = np.where(

531, unique wsis in selected set

In [10]:
df_wsi.keys()

Index(['scanner_model', 'study_name', 'site', 'piece', 'piece2', 'stain',
       'ihc_antibody', 'fraction_for_ihc_biomarker_assessment', 'preparation',
       'rescan', 'scan_timestamp', 'Row_ID_key_n8278', 'multiple_RiDs',
       'multiple_RiD_values', 'new_wsi_uniq_id', 'new_file_name', 'exclusion',
       'exclusion_criteria', 'comment', 'select_primary', 'primary_selection',
       'total_slides', 'total_he', 'largest_identified_tumor', 'file_name',
       'total_tumor_area_mm2', 'File Path', 'exists', 'file_size',
       'cumsum_size', 'Batch Name'],
      dtype='object')

In [11]:
print(df_wsi.groupby('scanner_model')['file_name'].nunique())
# print(df_wsi.groupby('scanner_model')['tile_name'].nunique())

scanner_model
APERIO       8
PHILIPS    629
S360       264
XR1        503
XR2        445
Name: file_name, dtype: int64

In [27]:
print(batch_1_select.groupby('scanner_model_new')['file_name'].nunique())
print(batch_1_select.groupby('scanner_model_new')['tile_name'].nunique())

scanner_model_new
PHILIPS    204
XR         327
Name: file_name, dtype: int64
scanner_model_new
PHILIPS    6534519
XR         5960128
Name: tile_name, dtype: int64

In [ ]:
# sperate pools of wsis for train and test, slect 300 wsis for training pool and 200 wsis for test pool, each has balanced scanner_model_new
_, df_train, df_test = stratified_split_one_df_slide(batch_1_select, 
                                                     var='scanner_model_new',
                                                     n_train=150, 
                                                     n_test=50,
                                                     random_state=42)  # or your column name
print(f'train tiles: {len(df_train)}, test tiles {len(df_test)}')
df_train.scanner_model_new.value_counts()

Per-stratum counts:
split              test  train
scanner_model_new
PHILIPS              50    150
XR                   50    150
train tiles: 7318324, test tiles 2615246

scanner_model_new
PHILIPS    4733590
XR         2584734
Name: count, dtype: int64

In [ ]:
# Training samples: select tiles for training from training wsi pool, slect 5 million tiles for training and 20000 tiles for validation, each has balanced scanner_model_new
df_train_split = stratified_split_one_df_tile(df_train, 
                                            var='scanner_model_new',
                                            random_state=32, 
                                            n_train=2500000, 
                                            n_test=10000)  # or your column name
df_train_split['folder_name'] = (
    '/mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_1/tiles/' + 
    df_train_split['file_name'] + '/' + df_train_split['file_name'] + '/')

df_train_split['crude_tile_path'] = df_train_split['folder_name'] + df_train_split['tile_name']
df_train_split.to_csv("/mnt/ssd/bojing/Image-Adaptive-3DLUT/dataframes/scanb_malmo_philips_xr_train.csv", 
                      index=False)

Per-stratum counts:
split               test    train
scanner_model_new
PHILIPS            10000  2500000
XR                 10000  2500000

In [ ]:
# Testing samples: use all tiles from test wsi pool
df_test['split'] = 'test'
df_test['folder_name'] = (
    '/mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_1/tiles/' + df_test['file_name'] + '/' + df_test['file_name'] + '/')

df_test['crude_tile_path'] = df_test['folder_name'] + df_test['tile_name']
df_test.to_csv("/mnt/ssd/bojing/Image-Adaptive-3DLUT/dataframes/scanb_malmo_philips_xr_test.csv"
               ,index=False)

/tmp/ipykernel_3422223/3645872904.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['split'] = 'test'
/tmp/ipykernel_3422223/3645872904.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['folder_name'] = (
/tmp/ipykernel_3422223/3645872904.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['crude_tile_path'] = df_test['folder_name'] + df_test['tile_name']

#### select the same tiles as in the test set, but with Macenko normalization

In [ ]:
# read in test set
df_test = pd.read_csv("/mnt/ssd/bojing/Image-Adaptive-3DLUT/dataframes/scanb_malmo_philips_xr_test.csv"
               ,index_col=False)
len(df_test)

2615246

In [5]:
# read in machenko processed tiles for test set
file_path_macenko = "/mnt/chime-preprocessed_data/SCANB_Malmo/SCANB_Malmo_224x224/processed-data/SCANB_Malmo_pil_10.4_224px/batches/Batch_1/dataframes/all_macenko_tiles.pkl"
batch_1_macenko = pd.read_pickle(file_path_macenko)
batch_1_macenko_select = batch_1_macenko[batch_1_macenko['file_name'].isin(df_test['file_name'].unique().tolist())]
batch_1_macenko_select.head();

                                          file_name  ...                                                                                                                                                                                            macenko_tile_path
127013  SCANB_MALMO_RiDn2806_slide_109936_WSI_clean  ...  /tmp/conboi/SCANB_Malmo_proc_data/batches/Batch_1/macenko_normalisation/tiles_macenko/SCANB_MALMO_RiDn2806_slide_109936_WSI_clean/SCANB_MALMO_RiDn2806_slide_109936_WSI_clean_0_405_29232_29637_macenko.jpg
127014  SCANB_MALMO_RiDn2806_slide_109936_WSI_clean  ...  /tmp/conboi/SCANB_Malmo_proc_data/batches/Batch_1/macenko_normalisation/tiles_macenko/SCANB_MALMO_RiDn2806_slide_109936_WSI_clean/SCANB_MALMO_RiDn2806_slide_109936_WSI_clean_0_405_29638_30043_macenko.jpg
127015  SCANB_MALMO_RiDn2806_slide_109936_WSI_clean  ...  /tmp/conboi/SCANB_Malmo_proc_data/batches/Batch_1/macenko_normalisation/tiles_macenko/SCANB_MALMO_RiDn2806_slide_109936_WSI_clean/SCANB_MALMO_RiDn2806_slide_109936_WSI_clean_0_405_30044_30449_macenko.jpg
127016  SCANB_MALMO_RiDn2806_slide_109936_WSI_clean  ...  /tmp/conboi/SCANB_Malmo_proc_data/batches/Batch_1/macenko_normalisation/tiles_macenko/SCANB_MALMO_RiDn2806_slide_109936_WSI_clean/SCANB_MALMO_RiDn2806_slide_109936_WSI_clean_0_405_30450_30855_macenko.jpg
127017  SCANB_MALMO_RiDn2806_slide_109936_WSI_clean  ...  /tmp/conboi/SCANB_Malmo_proc_data/batches/Batch_1/macenko_normalisation/tiles_macenko/SCANB_MALMO_RiDn2806_slide_109936_WSI_clean/SCANB_MALMO_RiDn2806_slide_109936_WSI_clean_0_405_30856_31261_macenko.jpg

[5 rows x 17 columns]

In [ ]:
# correct tile paths
batch_1_macenko_select['folder_name'] = (
    '/mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_1/macenko_normalisation/tiles_macenko/' + batch_1_macenko_select['file_name'] + '/' + batch_1_macenko_select['file_name'] + '/')
batch_1_macenko_select['macenko_tile_name'] = batch_1_macenko_select['macenko_tile_path'].str.split('/').str[-1]
batch_1_macenko_select['macenko_tile_path'] =batch_1_macenko_select['folder_name'] + batch_1_macenko_select['macenko_tile_name']
batch_1_macenko_select = batch_1_macenko_select.reset_index(drop=True)
batch_1_macenko_select.to_csv("/mnt/ssd/bojing/Image-Adaptive-3DLUT/dataframes/scanb_malmo_philips_xr_test_macenko.csv"
               ,index=False)

/tmp/ipykernel_22366/1926767189.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  batch_1_macenko_select['folder_name'] = (
/tmp/ipykernel_22366/1926767189.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  batch_1_macenko_select['macenko_tile_name'] = batch_1_macenko_select['macenko_tile_path'].str.split('/').str[-1]
/tmp/ipykernel_22366/1926767189.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  batch_1_macenko_select['macenko_tile_path'] =batch_1_macenko_select['folder_name'] + batch_1_macenko_select['macenko_tile_name']

In [19]:
len(batch_1_macenko_select)

2615246

In [6]:
import gc
gc.collect()

21

# New data using more than one scanner

In [10]:
# wsi list with scanner_model
df_wsi = pd.read_csv("/mnt/chime-preprocessed_data/SCANB_Malmo/SCANB_Malmo_224x224/df_batch_SCANB_Malmo_224x224.csv", index_col=False)
len(df_wsi)
df_wsi = df_wsi.rename(columns={"slide_filename": "file_name"})

# batch_1 crude tiles with macenko_blur
file_path = "/mnt/chime-preprocessed_data/SCANB_Malmo/SCANB_Malmo_224x224/processed-data/SCANB_Malmo_pil_10.4_224px/batches/Batch_1/dataframes/all_tiles_blur.csv"
batch_1 = pd.read_csv(file_path)

file_path = "/mnt/chime-preprocessed_data/SCANB_Malmo/SCANB_Malmo_224x224/processed-data/SCANB_Malmo_pil_10.4_224px/batches/Batch_2/dataframes/all_tiles_blur.csv"
batch_2 = pd.read_csv(file_path)

file_path = "/mnt/chime-preprocessed_data/SCANB_Malmo/SCANB_Malmo_224x224/processed-data/SCANB_Malmo_pil_10.4_224px/batches/Batch_3/dataframes/all_tiles_blur.csv"
batch_3 = pd.read_csv(file_path)

batch_1_2 = pd.concat([batch_1, batch_2, batch_3])

# merge with tile list
batch_1_2= pd.merge(batch_1_2, df_wsi[['file_name', 'scanner_model']], on = 'file_name', how='left')

#mask = (batch_1['tissue_proportion']==1) & (batch_1['macenko_blur']> 500) & (batch_1['scanner_model'].isin(['XR2', 'PHILIPS', 'XR1']))
mask = batch_1_2['scanner_model'].isin(['S360']) # make it general to use all tiles 
S360_select = batch_1_2[mask]


print(S360_select.scanner_model.value_counts(normalize=True))
S360_select['scanner_model_new'] = S360_select['scanner_model']


print(f'{S360_select.file_name.nunique()}, unique wsis in selected set')

scanner_model
S360    1.0
Name: proportion, dtype: float64

/tmp/ipykernel_166301/1280962330.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  S360_select['scanner_model_new'] = S360_select['scanner_model']

263, unique wsis in selected set

In [ ]:
print(S360_select.groupby('scanner_model')['file_name'].nunique())
print(S360_select.scanner_model.value_counts())

scanner_model
S360    263
Name: file_name, dtype: int64
scanner_model
S360    5838478
Name: count, dtype: int64

In [ ]:
for i in range(1,5):
    # file_path = "/mnt/chime-preprocessed_data/SCANB_Malmo/SCANB_Malmo_224x224/processed-data/SCANB_Malmo_pil_10.4_224px/batches/Batch_"+ str(i) +"/dataframes/all_tiles_blur.csv"
    # batch = pd.read_csv(file_path)
    # # merge with tile list
    # batch= pd.merge(batch, df_wsi[['file_name', 'scanner_model']], on = 'file_name', how='left')
    # print(batch.groupby('scanner_model')['file_name'].nunique())

scanner_model
APERIO       2
PHILIPS    204
S360        78
XR1        189
XR2        138
Name: file_name, dtype: int64
scanner_model
APERIO       3
PHILIPS    214
S360       101
XR1        155
XR2        147
Name: file_name, dtype: int64
scanner_model
APERIO       3
PHILIPS    208
S360        84
XR1        155
XR2        156
Name: file_name, dtype: int64
scanner_model
PHILIPS    3
S360       1
XR1        4
XR2        4
Name: file_name, dtype: int64

In [84]:
62+83+78

223

In [103]:
# sperate pools of wsis for train and test, slect 300 wsis for training pool and 200 wsis for test pool, each has balanced scanner_model_new
_, df_train_360, df_test_360 = stratified_split_one_df_slide(S360_select, 
                                                     var='scanner_model_new',
                                                     n_train=150, 
                                                     n_test=50,
                                                     random_state=42)  # or your column name
print(f'train tiles: {len(df_train_360)}, test tiles {len(df_test_360)}')
df_train_360.scanner_model_new.value_counts()

Per-stratum counts:
split              test  train
scanner_model_new
S360                 50    150
train tiles: 3242720, test tiles 1167979

scanner_model_new
S360    3242720
Name: count, dtype: int64

In [104]:
# Training samples: select tiles for training from training wsi pool, slect 5 million tiles for training and 20000 tiles for validation, each has balanced scanner_model_new
df_train_split_360 = stratified_split_one_df_tile(df_train_360, 
                                            var='scanner_model_new',
                                            random_state=32, 
                                            n_train=2500000, 
                                            n_test=10000)  # or your column name
# df_train_split['folder_name'] = (
#     '/mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_1/tiles/' + 
#     df_train_split['file_name'] + '/' + df_train_split['file_name'] + '/')

# df_train_split['crude_tile_path'] = df_train_split['folder_name'] + df_train_split['tile_name']
# df_train_split.to_csv("/mnt/ssd/bojing/Image-Adaptive-3DLUT/dataframes/scanb_malmo_philips_xr_train.csv", 
#                       index=False)

Per-stratum counts:
split               test    train
scanner_model_new
S360               10000  2500000

In [ ]:
df_train_split_360.to_csv("/mnt/ssd/ferbue/Image-Adaptive-3DLUT/dataframes/scanb_malmo_s360_train_ongoing.csv", 
                      index=False)

df_test_360.to_csv("/mnt/ssd/ferbue/Image-Adaptive-3DLUT/dataframes/scanb_malmo_s360_test_ongoing.csv"
               ,index=False)

In [ ]:
df_train_split_360['crude_tile_path'].str.replace('/tmp/conboi/SCANB_Malmo_proc_data/batches/', '', regex=False).to_csv('/mnt/ssd/ferbue/Image-Adaptive-3DLUT/dataframes/s360_train_relative_file_list.txt', index=False, header=False)

In [18]:
df_test_360['crude_tile_path'].str.replace('/tmp/conboi/SCANB_Malmo_proc_data/batches/', '', regex=False).to_csv('/mnt/ssd/ferbue/Image-Adaptive-3DLUT/dataframes/s360_test_relative_file_list.txt', index=False, header=False)
df_test_360['crude_tile_path'].str.replace('/tmp/conboi/SCANB_Malmo_proc_data/batches/', '', regex=False)

980070          Batch_1/tiles/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean_4410_4850_88200_88640.jpg
980071          Batch_1/tiles/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean_4410_4850_88641_89081.jpg
980072          Batch_1/tiles/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean_4851_5291_43218_43658.jpg
980073          Batch_1/tiles/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean_4851_5291_43659_44099.jpg
980074          Batch_1/tiles/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean_4851_5291_87318_87758.jpg
                                                                           ...
41952572    Batch_3/tiles/SCANB_MALMO_RiDn1173_slide_514000_WSI_clean/SCANB_MALMO_RiDn1173_slide_514000_WSI_clean_79821_80261_110250_110690.jpg
41952573    Batch_3/tiles/SCANB_MALMO_RiDn1173_slide_514000_WSI_clean/SCANB_MALMO_RiDn1173_slide_514000_WSI_clean_79821_80261_113337_113777.jpg
41952574    Batch_3/tiles/SCANB_MALMO_RiDn1173_slide_514000_WSI_clean/SCANB_MALMO_RiDn1173_slide_514000_WSI_clean_79821_80261_113778_114218.jpg
41952575    Batch_3/tiles/SCANB_MALMO_RiDn1173_slide_514000_WSI_clean/SCANB_MALMO_RiDn1173_slide_514000_WSI_clean_79821_80261_115101_115541.jpg
41952576    Batch_3/tiles/SCANB_MALMO_RiDn1173_slide_514000_WSI_clean/SCANB_MALMO_RiDn1173_slide_514000_WSI_clean_79821_80261_115542_115982.jpg
Name: crude_tile_path, Length: 1167979, dtype: object

Now we need to copy files.
- Checked with Bojing.

Should copy the files keeping the folder structure /Batch_1/tiles/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean_4410_4850_88200_88640.jpg
RUN FROM /home/ferbue/Image-Adaptive-3DLUT/
the syntax --files-from=relative_list.txt source_folder dst_folder
nohup rsync -av --info=progress2 --files-from=/mnt/ssd/ferbue/Image-Adaptive-3DLUT/dataframes/s360_test_relative_file_list.txt /mnt/chimeracknas5data2/preproc-slides/SCANB_MALMO/SCANB_Malmo_224x224/processed-data/SCANB_Malmo_pil_10.4_224px/batches/ /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/ > rsync_log_s360_test.txt 2>&1 &
170738 PID

In [105]:
df_train_split_360

                                            file_name  ...  split
34583992  SCANB_MALMO_RiDn4550_slide_135750_WSI_clean  ...  train
13068767  SCANB_MALMO_RiDn2010_slide_751619_WSI_clean  ...  train
30999376  SCANB_MALMO_RiDn4883_slide_885306_WSI_clean  ...  train
41400159  SCANB_MALMO_RiDn7987_slide_445333_WSI_clean  ...  train
23332913  SCANB_MALMO_RiDn2943_slide_695751_WSI_clean  ...  train
...                                               ...  ...    ...
32485419  SCANB_MALMO_RiDn6246_slide_829109_WSI_clean  ...   test
28054755  SCANB_MALMO_RiDn5614_slide_649156_WSI_clean  ...   test
34245178  SCANB_MALMO_RiDn7911_slide_509423_WSI_clean  ...   test
19429754  SCANB_MALMO_RiDn1660_slide_692168_WSI_clean  ...   test
29440030  SCANB_MALMO_RiDn6754_slide_792508_WSI_clean  ...   test

[2510000 rows x 19 columns]

In [112]:
df_train_split_360['crude_tile_path'].str.rsplit('/', n=1, expand=True)[0].str.replace('/tmp/conboi/SCANB_Malmo_proc_data/batches','/mnt/ssd/bojing/Image-Adaptive-3DLUT/data')+ '/'+df_train_split_360['file_name'] + '/'

34583992    /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_3/tiles/SCANB_MALMO_RiDn4550_slide_135750_WSI_clean/SCANB_MALMO_RiDn4550_slide_135750_WSI_clean/
13068767    /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_1/tiles/SCANB_MALMO_RiDn2010_slide_751619_WSI_clean/SCANB_MALMO_RiDn2010_slide_751619_WSI_clean/
30999376    /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_3/tiles/SCANB_MALMO_RiDn4883_slide_885306_WSI_clean/SCANB_MALMO_RiDn4883_slide_885306_WSI_clean/
41400159    /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_3/tiles/SCANB_MALMO_RiDn7987_slide_445333_WSI_clean/SCANB_MALMO_RiDn7987_slide_445333_WSI_clean/
23332913    /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_2/tiles/SCANB_MALMO_RiDn2943_slide_695751_WSI_clean/SCANB_MALMO_RiDn2943_slide_695751_WSI_clean/
                                                                                  ...
32485419    /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_3/tiles/SCANB_MALMO_RiDn6246_slide_829109_WSI_clean/SCANB_MALMO_RiDn6246_slide_829109_WSI_clean/
28054755    /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_2/tiles/SCANB_MALMO_RiDn5614_slide_649156_WSI_clean/SCANB_MALMO_RiDn5614_slide_649156_WSI_clean/
34245178    /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_3/tiles/SCANB_MALMO_RiDn7911_slide_509423_WSI_clean/SCANB_MALMO_RiDn7911_slide_509423_WSI_clean/
19429754    /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_2/tiles/SCANB_MALMO_RiDn1660_slide_692168_WSI_clean/SCANB_MALMO_RiDn1660_slide_692168_WSI_clean/
29440030    /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_3/tiles/SCANB_MALMO_RiDn6754_slide_792508_WSI_clean/SCANB_MALMO_RiDn6754_slide_792508_WSI_clean/
Length: 2510000, dtype: object

In [113]:
df_train_split_360['folder_name'] = (
    df_train_split_360['crude_tile_path'].str.rsplit('/', n=1, expand=True)[0].str.replace('/tmp/conboi/SCANB_Malmo_proc_data/batches','/mnt/ssd/bojing/Image-Adaptive-3DLUT/data')+ '/'+df_train_split_360['file_name'] + '/')

df_train_split_360['crude_tile_path'] = df_train_split_360['folder_name'] + df_train_split_360['tile_name'] # 


# Testing samples: use all tiles from test wsi pool
df_test_360['split'] = 'test'
df_test_360['folder_name'] = (
    df_test_360['crude_tile_path'].str.rsplit('/', n=1, expand=True)[0].str.replace('/tmp/conboi/SCANB_Malmo_proc_data/batches','/mnt/ssd/bojing/Image-Adaptive-3DLUT/data')+ '/'+df_test_360['file_name'] + '/')

df_test_360['crude_tile_path'] = df_test_360['folder_name'] + df_test_360['tile_name']

/tmp/ipykernel_166301/483537277.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test_360['split'] = 'test'
/tmp/ipykernel_166301/483537277.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test_360['folder_name'] = (
/tmp/ipykernel_166301/483537277.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test_360['crude_tile_path'] = df_test_360['folder_name'] + df_test_360['tile_name']

In [114]:
df_test_360

                                            file_name  ...                                                                                                                                       folder_name
980070    SCANB_MALMO_RiDn4140_slide_671222_WSI_clean  ...  /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_1/tiles/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/
980071    SCANB_MALMO_RiDn4140_slide_671222_WSI_clean  ...  /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_1/tiles/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/
980072    SCANB_MALMO_RiDn4140_slide_671222_WSI_clean  ...  /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_1/tiles/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/
980073    SCANB_MALMO_RiDn4140_slide_671222_WSI_clean  ...  /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_1/tiles/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/
980074    SCANB_MALMO_RiDn4140_slide_671222_WSI_clean  ...  /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_1/tiles/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/
...                                               ...  ...                                                                                                                                               ...
41952572  SCANB_MALMO_RiDn1173_slide_514000_WSI_clean  ...  /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_3/tiles/SCANB_MALMO_RiDn1173_slide_514000_WSI_clean/SCANB_MALMO_RiDn1173_slide_514000_WSI_clean/
41952573  SCANB_MALMO_RiDn1173_slide_514000_WSI_clean  ...  /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_3/tiles/SCANB_MALMO_RiDn1173_slide_514000_WSI_clean/SCANB_MALMO_RiDn1173_slide_514000_WSI_clean/
41952574  SCANB_MALMO_RiDn1173_slide_514000_WSI_clean  ...  /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_3/tiles/SCANB_MALMO_RiDn1173_slide_514000_WSI_clean/SCANB_MALMO_RiDn1173_slide_514000_WSI_clean/
41952575  SCANB_MALMO_RiDn1173_slide_514000_WSI_clean  ...  /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_3/tiles/SCANB_MALMO_RiDn1173_slide_514000_WSI_clean/SCANB_MALMO_RiDn1173_slide_514000_WSI_clean/
41952576  SCANB_MALMO_RiDn1173_slide_514000_WSI_clean  ...  /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_3/tiles/SCANB_MALMO_RiDn1173_slide_514000_WSI_clean/SCANB_MALMO_RiDn1173_slide_514000_WSI_clean/

[1167979 rows x 20 columns]

In [5]:
#Read previous Philips_XR Data
test_path = '/mnt/ssd/bojing/Image-Adaptive-3DLUT/dataframes/scanb_malmo_philips_xr_test.csv'
train_path = '/mnt/ssd/bojing/Image-Adaptive-3DLUT/dataframes/scanb_malmo_philips_xr_train.csv'

prev_train_df = pd.read_csv(train_path ,index_col=False)
prev_train_df.scanner_model_new.value_counts()

scanner_model_new
PHILIPS    2510000
XR         2510000
Name: count, dtype: int64

In [6]:
train_xr_df = prev_train_df[prev_train_df['scanner_model_new']=='XR']
print(len(train_xr_df))
train_philips_df = prev_train_df[prev_train_df['scanner_model_new']=='PHILIPS']
print(len(train_philips_df))

2510000
2510000

In [115]:
df_train_split_s360_xr = pd.concat([df_train_split_360, train_xr_df])
df_train_split_s360_xr.scanner_model_new.value_counts()

scanner_model_new
S360    2510000
XR      2510000
Name: count, dtype: int64

In [116]:
df_train_split_s360_xr.to_csv("/mnt/ssd/ferbue/Image-Adaptive-3DLUT/dataframes/scanb_malmo_s360_xr_train.csv", 
                      index=False)

In [27]:
#Read previous Philips_XR Data

prev_test_df = pd.read_csv(test_path ,index_col=False)
prev_test_df.scanner_model_new.value_counts()

test_xr_df = prev_test_df[prev_test_df['scanner_model_new']=='XR']
print(len(test_xr_df))
test_philips_df = prev_test_df[prev_test_df['scanner_model_new']=='PHILIPS']
print(len(test_philips_df))

958549
1656697

In [117]:
df_test_split_s360_xr = pd.concat([df_test_360, test_xr_df])
df_test_split_s360_xr.scanner_model_new.value_counts()

scanner_model_new
S360    1167979
XR       958549
Name: count, dtype: int64

In [118]:
df_test_split_s360_xr.to_csv("/mnt/ssd/ferbue/Image-Adaptive-3DLUT/dataframes/scanb_malmo_s360_xr_test.csv", 
                      index=False)

In [119]:
df_train_split_s360_xr_philips = pd.concat([df_train_split_360, train_philips_df, train_xr_df])
print(df_train_split_s360_xr_philips.scanner_model_new.value_counts())
df_train_split_s360_xr_philips.to_csv("/mnt/ssd/ferbue/Image-Adaptive-3DLUT/dataframes/scanb_malmo_s360_xr_philips_train.csv", index=False)

scanner_model_new
S360       2510000
PHILIPS    2510000
XR         2510000
Name: count, dtype: int64

In [32]:
print(df_train_split_s360_xr_philips.scanner_model_new.value_counts())

scanner_model_new
S360       2510000
PHILIPS    2510000
XR         2510000
Name: count, dtype: int64

In [120]:
df_test_split_s360_xr_philips = pd.concat([df_test_360, test_philips_df, test_xr_df])
print(df_test_split_s360_xr_philips.scanner_model_new.value_counts())
df_test_split_s360_xr_philips.to_csv("/mnt/ssd/ferbue/Image-Adaptive-3DLUT/dataframes/scanb_malmo_s360_xr_philips_test.csv", index=False)

scanner_model_new
PHILIPS    1656697
S360       1167979
XR          958549
Name: count, dtype: int64

In [69]:
import glob
import tarfile
from tqdm import tqdm
import os

In [74]:
df_test_360[df_test_360['file_name']==wsi]

                                           file_name  ...                                                                                                                                       folder_name
980070   SCANB_MALMO_RiDn4140_slide_671222_WSI_clean  ...  /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_1/tiles/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/
980071   SCANB_MALMO_RiDn4140_slide_671222_WSI_clean  ...  /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_1/tiles/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/
980072   SCANB_MALMO_RiDn4140_slide_671222_WSI_clean  ...  /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_1/tiles/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/
980073   SCANB_MALMO_RiDn4140_slide_671222_WSI_clean  ...  /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_1/tiles/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/
980074   SCANB_MALMO_RiDn4140_slide_671222_WSI_clean  ...  /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_1/tiles/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/
...                                              ...  ...                                                                                                                                               ...
1007558  SCANB_MALMO_RiDn4140_slide_671222_WSI_clean  ...  /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_1/tiles/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/
1007559  SCANB_MALMO_RiDn4140_slide_671222_WSI_clean  ...  /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_1/tiles/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/
1007560  SCANB_MALMO_RiDn4140_slide_671222_WSI_clean  ...  /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_1/tiles/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/
1007561  SCANB_MALMO_RiDn4140_slide_671222_WSI_clean  ...  /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_1/tiles/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/
1007562  SCANB_MALMO_RiDn4140_slide_671222_WSI_clean  ...  /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_1/tiles/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/SCANB_MALMO_RiDn4140_slide_671222_WSI_clean/

[27493 rows x 20 columns]

In [ ]:
# Moving the data

source_folder = '/mnt/chimeracknas5data2/preproc-slides/SCANB_MALMO/SCANB_Malmo_224x224/processed-data/SCANB_Malmo_pil_10.4_224px/batches/'
target_folder_base = '/mnt/ssd/bojing/Image-Adaptive-3DLUT/data/'

for wsi in tqdm(df_test_360['file_name'].unique()[:]):
    # print(wsi)
    tar_file = glob.glob(source_folder+'*/tiles/'+wsi+'/*.tar')[0]
    batch = int(tar_file.replace(source_folder,'').split('/')[0].split('_')[-1])
    # if batch != 1: #I don't need to copy Batch 1, plus I don't have the writing permission
    if not os.path.isdir(target_folder_wsi): #
        target_folder_wsi = target_folder_base+tar_file.replace(source_folder,'').rsplit('/',1)[0]+'/'+wsi+'/' #Double wsi to match what was previously done
        with tarfile.open(tar_file) as tar:
            tar.extractall(path=target_folder_wsi)

100%|██████████| 50/50 [01:22<00:00,  1.65s/it]

In [88]:

# Repeating for missing files in processed data

source_folder = '/mnt/chimeracknas5data2/preproc-slides/SCANB_MALMO/SCANB_Malmo_all_slides_224x224/batches/'
target_folder_base = '/mnt/ssd/bojing/Image-Adaptive-3DLUT/data/'
missing=[]

for wsi in tqdm(df_test_360['file_name'].unique()[:]):
    # print(wsi)
    tar_file = glob.glob(source_folder+'*/tiles/'+wsi+'/*.tar')[0]
    batch = int(tar_file.replace(source_folder,'').split('/')[0].split('_')[-1])
    # if batch != 1: #I don't need to copy Batch 1, plus I don't have the writing permission
    if not os.path.isdir(target_folder_wsi): #
        missing.append(wsi)
        target_folder_wsi = target_folder_base+tar_file.replace(source_folder,'').rsplit('/',1)[0]+'/'+wsi+'/' #Double wsi to match what was previously done
        with tarfile.open(tar_file) as tar:
            tar.extractall(path=target_folder_wsi)

print('missing:',len(missing))

100%|██████████| 50/50 [00:01<00:00, 28.70it/s]

missing: 0

In [82]:
for wsi in tqdm(df_train_360['file_name'].unique()[:]):
    # print(wsi)
    tar_file = glob.glob(source_folder+'*/tiles/'+wsi+'/*.tar')[0]
    batch = int(tar_file.replace(source_folder,'').split('/')[0].split('_')[-1])
    if batch != 1:
        target_folder_wsi = target_folder_base+tar_file.replace(source_folder,'').rsplit('/',1)[0]+'/'+wsi+'/' #Double wsi to match what was previously done
        with tarfile.open(tar_file) as tar:
            tar.extractall(path=target_folder_wsi)

100%|██████████| 150/150 [04:07<00:00,  1.65s/it]

                                           file_name  ...                                                                                                                                       folder_name
288      SCANB_MALMO_RiDn2162_slide_111129_WSI_clean  ...  /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_1/tiles/SCANB_MALMO_RiDn2162_slide_111129_WSI_clean/SCANB_MALMO_RiDn2162_slide_111129_WSI_clean/
386      SCANB_MALMO_RiDn2162_slide_111129_WSI_clean  ...  /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_1/tiles/SCANB_MALMO_RiDn2162_slide_111129_WSI_clean/SCANB_MALMO_RiDn2162_slide_111129_WSI_clean/
1243     SCANB_MALMO_RiDn2162_slide_111129_WSI_clean  ...  /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_1/tiles/SCANB_MALMO_RiDn2162_slide_111129_WSI_clean/SCANB_MALMO_RiDn2162_slide_111129_WSI_clean/
2237     SCANB_MALMO_RiDn2162_slide_111129_WSI_clean  ...  /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_1/tiles/SCANB_MALMO_RiDn2162_slide_111129_WSI_clean/SCANB_MALMO_RiDn2162_slide_111129_WSI_clean/
2438     SCANB_MALMO_RiDn2162_slide_111129_WSI_clean  ...  /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_1/tiles/SCANB_MALMO_RiDn2162_slide_111129_WSI_clean/SCANB_MALMO_RiDn2162_slide_111129_WSI_clean/
...                                              ...  ...                                                                                                                                               ...
2507102  SCANB_MALMO_RiDn2162_slide_111129_WSI_clean  ...  /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_1/tiles/SCANB_MALMO_RiDn2162_slide_111129_WSI_clean/SCANB_MALMO_RiDn2162_slide_111129_WSI_clean/
2507628  SCANB_MALMO_RiDn2162_slide_111129_WSI_clean  ...  /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_1/tiles/SCANB_MALMO_RiDn2162_slide_111129_WSI_clean/SCANB_MALMO_RiDn2162_slide_111129_WSI_clean/
2507904  SCANB_MALMO_RiDn2162_slide_111129_WSI_clean  ...  /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_1/tiles/SCANB_MALMO_RiDn2162_slide_111129_WSI_clean/SCANB_MALMO_RiDn2162_slide_111129_WSI_clean/
2508568  SCANB_MALMO_RiDn2162_slide_111129_WSI_clean  ...  /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_1/tiles/SCANB_MALMO_RiDn2162_slide_111129_WSI_clean/SCANB_MALMO_RiDn2162_slide_111129_WSI_clean/
2509982  SCANB_MALMO_RiDn2162_slide_111129_WSI_clean  ...  /mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_1/tiles/SCANB_MALMO_RiDn2162_slide_111129_WSI_clean/SCANB_MALMO_RiDn2162_slide_111129_WSI_clean/

[3925 rows x 20 columns]

In [ ]:
check_df = pd.read_csv("/mnt/ssd/ferbue/Image-Adaptive-3DLUT/dataframes/scanb_malmo_s360_xr_philips_train.csv")

missing = []
for wsi in tqdm(df_test_360['file_name'].unique()[:]):
    tar_file = glob.glob(source_folder+'*/tiles/'+wsi+'/*.tar')[0]
    batch = tar_file.replace(source_folder,'').split('/')[0]
    if batch!= 'Batch_1':
        missing.append(wsi)
        check_df.loc[check_df['file_name'] == wsi, 'folder_name'] = check_df.loc[check_df['file_name'] == wsi, 'folder_name'].str.replace('Batch_1', batch, regex=False)
        check_df.loc[check_df['file_name'] == wsi, 'crude_tile_path'] = check_df.loc[check_df['file_name'] == wsi, 'crude_tile_path'].str.replace('Batch_1', batch, regex=False)
print(len(missing))

100%|██████████| 50/50 [01:43<00:00,  2.07s/it]

48

In [102]:
check_df.to_csv("/mnt/ssd/ferbue/Image-Adaptive-3DLUT/dataframes/scanb_malmo_s360_xr_philips_test.csv", index=False)

In [94]:
# check_df[check_df['file_name']=='SCANB_MALMO_RiDn2162_slide_111129_WSI_clean']
'SCANB_MALMO_RiDn2162_slide_111129_WSI_clean' in df_train_360['file_name'].unique()[:]

glob.glob(target_folder_base+'/*/tiles/'+ 'SCANB_MALMO_RiDn2162_slide_111129_WSI_clean')

['/mnt/ssd/bojing/Image-Adaptive-3DLUT/data/Batch_2/tiles/SCANB_MALMO_RiDn2162_slide_111129_WSI_clean']